version: '3.8'
services:
  mlops_service:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app  # Mapea el directorio actual al directorio /app del contenedor
    ports:
      - "8888:8888"  # Puerto para Jupyter o cualquier otro servicio expuesto
      - "5002:5002"  # Puerto para tu aplicación Flask u otra API
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      bash -c "cat requirements.txt | xargs -n 1 pip install --no-cache-dir || echo 'Some dependencies failed to install.' && tail -f /dev/null"